//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _804ManchesterHomeControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public Device()
        {
            this.DeviceCommands = new HashSet<DeviceCommand>();
        }
    
        public string DeviceName { get; set; }
        public Nullable<int> SerialPort { get; set; }
        public Nullable<int> BaudRate { get; set; }
        public int Id { get; set; }
        public Boolean HexMode { get; set; }
    
        public virtual ICollection<DeviceCommand> DeviceCommands { get; set; }
    }
}
