//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _804ManchesterHomeControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceCommand
    {
        public DeviceCommand()
        {
            this.RequiredCommands = new HashSet<RequiredCommand>();
        }
    
        public int Id { get; set; }
        public int DeviceId { get; set; }
        public string Name { get; set; }
        public string IRCode { get; set; }
        public string URL { get; set; }
        public string SerialCommand { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual ICollection<RequiredCommand> RequiredCommands { get; set; }
    }
}
