//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _804ManchesterHomeControl.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDatabaseEntities : DbContext
    {
        public MyDatabaseEntities()
            : base("name=MyDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Device> Devices { get; set; }
        public DbSet<Activity> Activities { get; set; }
        public DbSet<DeviceCommand> DeviceCommands { get; set; }
        public DbSet<RequiredCommand> RequiredCommands { get; set; }
        public DbSet<RoomActivity> RoomActivities { get; set; }
        public DbSet<Room> Rooms { get; set; }
    }
}
