//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _804ManchesterHomeControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.RoomActivities = new HashSet<RoomActivity>();
        }
    
        public int Id { get; set; }
        public string RoomName { get; set; }
    
        public virtual ICollection<RoomActivity> RoomActivities { get; set; }
    }
}
