//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _804ManchesterHomeControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomActivity
    {
        public RoomActivity()
        {
            this.RequiredCommands = new HashSet<RequiredCommand>();
        }
    
        public int Id { get; set; }
        public int RoomId { get; set; }
        public int ActivityId { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual ICollection<RequiredCommand> RequiredCommands { get; set; }
        public virtual Room Room { get; set; }
    }
}
